In [1]:
# first neural network with keras tutorial
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense

In [3]:
# load the dataset
dataset = loadtxt('pima-indians-diabetes.data.txt', delimiter=',')

In [4]:
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [5]:
# split into input (X) and output (y) variables
X = dataset[:, 0:8]
y = dataset[:, 8]

In [6]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [7]:
y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [8]:
# define the keras model
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [9]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [10]:
# fit the keras model on th dataset
model.fit(X, y, epochs=150, batch_size=10)

Epoch 1/150
77/77 [==============================] - 2s 624us/step - loss: 7.2484 - accuracy: 0.3893
Epoch 2/150
77/77 [==============================] - 0s 587us/step - loss: 1.3293 - accuracy: 0.6146
Epoch 3/150
77/77 [==============================] - 0s 604us/step - loss: 0.9048 - accuracy: 0.6250
Epoch 4/150
77/77 [==============================] - 0s 601us/step - loss: 0.7600 - accuracy: 0.6354
Epoch 5/150
77/77 [==============================] - 0s 575us/step - loss: 0.7069 - accuracy: 0.6341
Epoch 6/150
77/77 [==============================] - 0s 572us/step - loss: 0.6882 - accuracy: 0.6276
Epoch 7/150
77/77 [==============================] - 0s 571us/step - loss: 0.6727 - accuracy: 0.6302
Epoch 8/150
77/77 [==============================] - 0s 559us/step - loss: 0.6721 - accuracy: 0.6276
Epoch 9/150
77/77 [==============================] - 0s 551us/step - loss: 0.6577 - accuracy: 0.6315
Epoch 10/150
77/77 [==============================] - 0s 558us/step - loss: 0.6608 - accura

77/77 [==============================] - 0s 587us/step - loss: 0.5388 - accuracy: 0.6979
Epoch 82/150
77/77 [==============================] - 0s 588us/step - loss: 0.5414 - accuracy: 0.7083
Epoch 83/150
77/77 [==============================] - 0s 590us/step - loss: 0.5540 - accuracy: 0.6862
Epoch 84/150
77/77 [==============================] - 0s 585us/step - loss: 0.5535 - accuracy: 0.6901
Epoch 85/150
77/77 [==============================] - 0s 601us/step - loss: 0.5424 - accuracy: 0.6966
Epoch 86/150
77/77 [==============================] - 0s 582us/step - loss: 0.5397 - accuracy: 0.6888
Epoch 87/150
77/77 [==============================] - 0s 590us/step - loss: 0.5461 - accuracy: 0.7135
Epoch 88/150
77/77 [==============================] - 0s 596us/step - loss: 0.5386 - accuracy: 0.6940
Epoch 89/150
77/77 [==============================] - 0s 584us/step - loss: 0.5393 - accuracy: 0.6914
Epoch 90/150
77/77 [==============================] - 0s 586us/step - loss: 0.5353 - accuracy: 

In [11]:
# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print("Accuracy: %.2f" % (accuracy*100))

24/24 [==============================] - 0s 714us/step - loss: 0.4898 - accuracy: 0.7396
Accuracy: 73.96
